### PR TITLE
[issue-3] Add multiple criteria 'severity'

### PR DESCRIPTION
**Pull request by afdesk**

### CODE REVIEW

**Comment by jerbia** [comment]
I tried running the report generation for image "nginx:latest". Seems like there is an infinite loop in the REST API, where you don't stop iterating through pages (although there is only 1 page of vulnerabilities):


This is from the output:
Next severities will be selected:
* critical
/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=2&severity=critical
/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=3&severity=critical
/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=4&severity=critical
/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=5&severity=critical

**Comment by jerbia** [comment]
@afdesk can you support comma separated list of severities instead of providing the "-severity" multiple times?

**Comment by afdesk** [comment]
> @afdesk can you support comma separated list of severities instead of providing the "-severity" multiple times?

I did it. See last commit

**Comment by afdesk** [comment]
@jerbia can I resolve a merge conflict?

**Pull request merged**
